export { default as AppleLogo } from "./apple_logo 1.png";
export { default as Pro } from "./pro.jpg";
export { default as Iphone16 } from "./iphone16.jpg";
export { default as AppleWatch } from "./appleWatch.jpg";
export { default as AppleWatchUltra } from "./appleWatchUltra.jpg";
export { default as AirPods4 } from "./airPods4.jpg";
export { default as AirPodsPro2 } from "./airPodsPro2.jpg";
export { default as AirPodsMax } from "./airPodsMax.jpg";
export { default as Apple1 } from "./Appleimg1.png";
export { default as Apple2 } from "./Appleimg2.png";
export { default as Apple3 } from "./Appleimg3.png";
export { default as Noel } from "./noel.jpeg";
